### ISSUE TITLE
Update JUnit tests (might require code refactoring)

### ISSUE THREAD

**Issue by kjorg50** [UCSB-CS56-Projects/cs56-games-minesweeper#11]
There are multiple cases of unit tests in GridTest.java that are empty and contain comments like `//not able to test due to...`. Either these "skeleton" tests should be removed, or you should refactor the code in a way that makes it more easy to test. See some of Andrew Berls' comments on pull request #5 for some helpful comments

~estimated 200

**Comment by EasterAndJay** [comment]
W16 approved
