### ISSUE TITLE
JUnit tests for the GUI

### ISSUE THREAD

**Issue by kjorg50** [UCSB-CS56-Projects/cs56-games-minesweeper#12]
This doesn't depend on #11, but it would probably be good to do that issue first.

Since this game has a GUI interface, you should test it to make sure that button listeners perform the correct actions, and that the view of the game logic is displayed correctly. To do this, you will have to learn how to write some basic JUnit tests for GUIs. Using the Java [Robot](http://docs.oracle.com/javase/7/docs/api/java/awt/Robot.html) class should be helpful. Here is one link to get started looking for more info. There are some examples of how to use the Robot class on stackoverflow as well.

http://docs.oracle.com/javase/7/docs/api/java/awt/Robot.html

~estimated 200

**Comment by EasterAndJay** [comment]
W16 approved

**Comment by athielk** [comment]
F16 OK (300 pts)

**Comment by johnnyzhang1738** [comment]
F17 OK (300 Points)
