### ISSUE TITLE
Add saving functionality

### ISSUE THREAD

**Issue by calebnelson** [UCSB-CS56-Projects/cs56-games-minesweeper#19]
Make it so if the game is paused or interrupted in any way except for completion, it saves the current state of the grid as a file that can be reopened when the game is resumed or restarted. The best way to do this would probably be implementing Serializable on the Grid class and then working that functionality into the main game.

Estimated points 400

**Comment by mliou** [comment]
Approved.

**Comment by EasterAndJay** [comment]
Closed
