### ISSUE TITLE
Fix number hiding bug

### ISSUE THREAD

**Issue by calebnelson** [UCSB-CS56-Projects/cs56-games-minesweeper#21]
The size of the game board is dynamically sized to not exceed your screen size. However, for harder difficulties, this can cause the buttons to be so small that the numbers are not visible on the game board, making the game unplayable. Fix the text on the buttons so that the font is reduced as needed.

Estimated points 250

**Comment by mliou** [comment]
Approved.

**Comment by EasterAndJay** [comment]
Clsoed
