### ISSUE TITLE
Add images for flags and mines

### ISSUE THREAD

**Issue by mliou** [UCSB-CS56-Projects/cs56-games-minesweeper#22]
Right now, the mines are represented by X's, and flags are represented by F's. Replace these letters with actual images of mines and flags respectively.
~estimated 200 pts

**Comment by EasterAndJay** [comment]
W16 approved

**Comment by ije896** [comment]
A few more UX changes:
-If opened cell is 0, do not display 0, just change cell color to grey
-Overhaul entire cell structure to replace all chars with images (including numbers) 

Not sure about this request, but possibly add an additional ~100 points?

**Comment by athielk** [comment]
F16 OK (300 pts)

**Comment by johnnyzhang1738** [comment]
F17 OK (250 points)
