### ISSUE TITLE
Add Screen Change Helper Methods

### ISSUE THREAD

**Issue by ije896** [ucsb-cs56-projects/cs56-games-minesweeper#29]
Right now, the GUI manually switches between JPanels (game->menu, menu->help). Build helper methods that change between screens to clean up code. 

Estimated ~100 points

**Comment by mcaccamo** [comment]
m16 okay

**Comment by athielk** [comment]
F16 OK (100 pts)

**Comment by brianslee** [comment]
Fixed. Closed W18
