### ISSUE TITLE
Highscore Feature

### ISSUE THREAD

**Issue by ije896** [UCSB-CS56-Projects/cs56-games-minesweeper#30]
Assuming the timer is implemented, create a high score feature that allows users to see the high scores of everyone who has locally played the game. Consider game difficulty and user time as potential factors for creating high scores. 

Estimated ~250 points

**Comment by mcaccamo** [comment]
M16 Okay

**Comment by athielk** [comment]
F16 OK (250 pts)

**Comment by jimmylle** [comment]
Fixed in this [pull request](https://github.com/UCSB-CS56-Projects/cs56-games-minesweeper/pull/42).
