### ISSUE TITLE
Update Game Responses According to Game State

### ISSUE THREAD

**Issue by ije896** [UCSB-CS56-Projects/cs56-games-minesweeper#33]
Make the timer stop when you win or lose a game.

Change save functionality so it will not save your game data if you have just won or lost the game, or if the game you exited is an empty game.

Change dialogue message functionality so when you win or lose, the dialogue box buttons show 'Main Menu' and 'Reset Game' instead of simply 'Okay'.

Estimated ~200 points

**Comment by mcaccamo** [comment]
M16 Okay

**Comment by athielk** [comment]
F16 CLOSED: split it up into separate issues.
