### ISSUE TITLE
Expose Mines Once You Lose the Game

### ISSUE THREAD

**Issue by ije896** [UCSB-CS56-Projects/cs56-games-minesweeper#34]
Traditionally in minesweeper, when the player loses the game, all of the mine locations are exposed. Write a function that shows all mines and add this functionality to the GUI game.

Estimated ~100 points

**Comment by mcaccamo** [comment]
M16 OKAY

**Comment by athielk** [comment]
F16 OK (100 pts)

**Comment by jimmylle** [comment]
Fixed in this [pull request](https://github.com/UCSB-CS56-Projects/cs56-games-minesweeper/pull/42).

**Comment by xosherry** [comment]
Request for 250 points because it took a atleast 6.5 hours, due to existing methods/variables not being the most appropriate approach and ended up using new (to me) concepts that required learning curve.
