### ISSUE TITLE
Javadoc update

### ISSUE THREAD

**Issue by athielk** [UCSB-CS56-Projects/cs56-games-minesweeper#37]
use gh-pages workflow to publish javadoc to GitHub pages URL.   Do not have the javadoc in the .gitignore or copy it outside the repo.

**Comment by athielk** [comment]
F16 OK (100 pts)

**Comment by athielk** [comment]
F16 OK (100 pts)

**Comment by jimmylle** [comment]
Fixed, you can find the javadoc information [here](https://github.com/UCSB-CS56-Projects-Javadoc/cs56-games-minesweeper).
