### ISSUE TITLE
save function update.

### ISSUE THREAD

**Issue by athielk** [UCSB-CS56-Projects/cs56-games-minesweeper#39]
Change save functionality so it will not save your game data if you have just won or lost the game, or if the game you exited is an empty game.

**Comment by athielk** [comment]
F16 OK (100 pts)

**Comment by jimmylle** [comment]
@athielk Can you explain what you mean by empty game. Do you mean if you start a new game but haven't clicked on anything or do you mean something else.

**Comment by athielk** [comment]
The game is saved whenever minesweeper is closed, I thought it strange to save a game you have not done anything with.  But that ultimately is up to you.  this issue is more about decoupling closing and saving.

**Comment by jimmylle** [comment]
Fixed in this [pull request](https://github.com/UCSB-CS56-Projects/cs56-games-minesweeper/pull/41).
