### ISSUE TITLE
Fix bug in High Score functionality

### ISSUE THREAD

**Issue by johnnyzhang1738** [UCSB-CS56-Projects/cs56-games-minesweeper#43]
If "HighScore.txt" doesn't exist on your local machine, it will generate an error. Fix this issue by adding code which will generate a HighScore.txt file if it doesn't exist on the local machine. Estimated points 100

**Comment by jimmylle** [comment]
F16 OK (100 pts)

**Comment by johnnyzhang1738** [comment]
Fixed via database implementation
