### ISSUE TITLE
Add sounds

### ISSUE THREAD

**Issue by davidacevedo** [UCSB-CS56-Projects/cs56-games-minesweeper#6]
Minesweeper currently has no sounds whatsoever, but your job will be to add background sounds for when you open a box, and the sounds should be different for when you open a box that doesn't have a mine and open a box that does have a mine.
@andrewberls

**Comment by athielk** [comment]
what is the point estimation for this?

**Comment by EasterAndJay** [comment]
Approved 300 points

**Comment by EasterAndJay** [comment]
Closed
