### ISSUE TITLE
Change the menu

### ISSUE THREAD

**Issue by davidacevedo** [UCSB-CS56-Projects/cs56-games-minesweeper#7]
The menu was originally created as a start menu, but minesweeper doesn't really need a pause feature since the game doesn't need to pause, so your job here is to add a menu bar at the top of the screen that is similar to File, edit, etc at the top of any program screen that includes the new game and help in it.
@andrewberls 

~estimated 250

**Comment by EasterAndJay** [comment]
W16 approved

**Comment by ije896** [comment]
This issue required extensive refactoring of the original code. Requesting 300 points for issue.
