### ISSUE TITLE
UI Tune Up

### ISSUE THREAD

**Issue by davidacevedo** [UCSB-CS56-Projects/cs56-games-minesweeper#8]
The minesweeper game as of right now looks pretty ugly, your job is to make the UI nicer to the eye, basically make the colors nicer, take off the numbers from the unopened boxes, replace the big X's with a mine picture, and replace the flagged F's with a flag picture.

~estimated 250

**Comment by amazingcaleb** [comment]
I removed the numbers from the unopened boxes and added colors to the numbers of opened tiles, flags, and mines, but I did not use pictures for flags and mines. They are still represented with capital F's and X's.
